# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RouteCorrector
                                 A QGIS plugin
 Adjusts moving points to user-defined routes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-04
        copyright            : (C) 2025 by Ana Laura Jiménez Chávez_InIAT
        email                : analaura.jimenez.ch@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RouteCorrector class from file RouteCorrector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .route_corrector import RouteCorrector
    return RouteCorrector(iface)
